// Mocks generated by Mockito 5.4.4 from annotations
// in distrito_medico/test/features/event_procedures/domain/usecases/generate_event_procedure_pdf_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i8;

import 'package:dartz/dartz.dart' as _i2;
import 'package:distrito_medico/core/errors/failures.dart' as _i5;
import 'package:distrito_medico/features/event_procedures/domain/entities/event_procedure_entity.dart'
    as _i7;
import 'package:distrito_medico/features/event_procedures/domain/entities/event_procedure_result_entity.dart'
    as _i6;
import 'package:distrito_medico/features/event_procedures/domain/repositories/event_procedure_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EventProcedureRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventProcedureRepository extends _i1.Mock
    implements _i3.EventProcedureRepository {
  MockEventProcedureRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.EventProcedureResultEntity>>
      getEventProcedures({
    int? page = 1,
    int? perPage = 10,
    int? month,
    int? year,
    bool? paid,
    String? healthInsuranceName,
    String? hospitalName,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getEventProcedures,
              [],
              {
                #page: page,
                #perPage: perPage,
                #month: month,
                #year: year,
                #paid: paid,
                #healthInsuranceName: healthInsuranceName,
                #hospitalName: hospitalName,
              },
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, _i6.EventProcedureResultEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.EventProcedureResultEntity>(
              this,
              Invocation.method(
                #getEventProcedures,
                [],
                {
                  #page: page,
                  #perPage: perPage,
                  #month: month,
                  #year: year,
                  #paid: paid,
                  #healthInsuranceName: healthInsuranceName,
                  #hospitalName: hospitalName,
                },
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, _i6.EventProcedureResultEntity>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i7.EventProcedureEntity>> createEventProcedure({
    required int? hospitalId,
    required String? patientServiceNumber,
    required String? date,
    required String? roomType,
    required bool? urgency,
    String? paidAt,
    bool? paid,
    String? payment,
    required Map<String, dynamic>? healthInsuranceAttributes,
    required Map<String, dynamic>? patientAttributes,
    required Map<String, dynamic>? procedureAttributes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEventProcedure,
          [],
          {
            #hospitalId: hospitalId,
            #patientServiceNumber: patientServiceNumber,
            #date: date,
            #roomType: roomType,
            #urgency: urgency,
            #paidAt: paidAt,
            #paid: paid,
            #payment: payment,
            #healthInsuranceAttributes: healthInsuranceAttributes,
            #patientAttributes: patientAttributes,
            #procedureAttributes: procedureAttributes,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i7.EventProcedureEntity>>.value(
                _FakeEither_0<_i5.Failure, _i7.EventProcedureEntity>(
          this,
          Invocation.method(
            #createEventProcedure,
            [],
            {
              #hospitalId: hospitalId,
              #patientServiceNumber: patientServiceNumber,
              #date: date,
              #roomType: roomType,
              #urgency: urgency,
              #paidAt: paidAt,
              #paid: paid,
              #payment: payment,
              #healthInsuranceAttributes: healthInsuranceAttributes,
              #patientAttributes: patientAttributes,
              #procedureAttributes: procedureAttributes,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.EventProcedureEntity>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i7.EventProcedureEntity>> updateEventProcedure({
    required int? id,
    required int? hospitalId,
    required String? patientServiceNumber,
    required String? date,
    required String? roomType,
    required bool? urgency,
    String? paidAt,
    bool? paid,
    String? payment,
    required Map<String, dynamic>? healthInsuranceAttributes,
    required Map<String, dynamic>? patientAttributes,
    required Map<String, dynamic>? procedureAttributes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEventProcedure,
          [],
          {
            #id: id,
            #hospitalId: hospitalId,
            #patientServiceNumber: patientServiceNumber,
            #date: date,
            #roomType: roomType,
            #urgency: urgency,
            #paidAt: paidAt,
            #paid: paid,
            #payment: payment,
            #healthInsuranceAttributes: healthInsuranceAttributes,
            #patientAttributes: patientAttributes,
            #procedureAttributes: procedureAttributes,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i7.EventProcedureEntity>>.value(
                _FakeEither_0<_i5.Failure, _i7.EventProcedureEntity>(
          this,
          Invocation.method(
            #updateEventProcedure,
            [],
            {
              #id: id,
              #hospitalId: hospitalId,
              #patientServiceNumber: patientServiceNumber,
              #date: date,
              #roomType: roomType,
              #urgency: urgency,
              #paidAt: paidAt,
              #paid: paid,
              #payment: payment,
              #healthInsuranceAttributes: healthInsuranceAttributes,
              #patientAttributes: patientAttributes,
              #procedureAttributes: procedureAttributes,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.EventProcedureEntity>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i7.EventProcedureEntity>> updatePaymentStatus({
    required int? id,
    required bool? paid,
    String? paidAt,
    String? payment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePaymentStatus,
          [],
          {
            #id: id,
            #paid: paid,
            #paidAt: paidAt,
            #payment: payment,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i7.EventProcedureEntity>>.value(
                _FakeEither_0<_i5.Failure, _i7.EventProcedureEntity>(
          this,
          Invocation.method(
            #updatePaymentStatus,
            [],
            {
              #id: id,
              #paid: paid,
              #paidAt: paidAt,
              #payment: payment,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.EventProcedureEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteEventProcedure(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteEventProcedure,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteEventProcedure,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.Uint8List>> generatePdfReport({
    int? month,
    int? year,
    bool? paid,
    String? healthInsuranceName,
    String? hospitalName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generatePdfReport,
          [],
          {
            #month: month,
            #year: year,
            #paid: paid,
            #healthInsuranceName: healthInsuranceName,
            #hospitalName: hospitalName,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.Uint8List>>.value(
            _FakeEither_0<_i5.Failure, _i8.Uint8List>(
          this,
          Invocation.method(
            #generatePdfReport,
            [],
            {
              #month: month,
              #year: year,
              #paid: paid,
              #healthInsuranceName: healthInsuranceName,
              #hospitalName: hospitalName,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.Uint8List>>);
}
